spring:
  application:
    name: deal-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/deal-service-db
#    username: user
#    password: 1
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest


jwt:
  secret: some_secret_code_aasdk;j1239;lkasf9o8
  expiration: 1200000

logging:
  level:
    org:
      springframework:
        transaction: DEBUG
        jdbc:
          core: DEBUG
server:
  port: 8081